### ISSUE TITLE
simplify makefile

### ISSUE THREAD

**Issue by kulti** [kulti/task-list#26]
Makefile becomes too big and ugly. It does a lot of stuff. Other tools can probably do it better.

Things to research:
- docker images build
- deploy
- project structure to generalize makefile targets

Finally, things to be done:
- [x] Reorganize project source tree to simplify docker build - #34.
- [x] Move all dockerfile to separate directory - #39.
- [x] Add some configuration to docker-compose by env files - #35.
- [x] Push docker images to hub - #32.
- [x] Add a new target(st) to pull docker images and deploy them without building - #36.

**Comment by kulti** [comment]
1. Reorganize project source tree to simplify docker build - #34.
2. Add some configuration to docker-compose by env files - #35.
3. Push docker images to hub - #32.
4. Add a new target(st) to pull docker images and deploy them without building - #36.
